### ISSUE TITLE
Login not Working

### ISSUE THREAD

**Issue by nicco2803** [bym-refitted/backyard-monsters-refitted#117]
My Login is not working success in Registration but can not Play the Game from Germany. Are there any country restrictions?

Best

**Comment by tram98** [comment]
Hi @nicco2803 ,

can you please describe what happens when you try to log in? A screenshot would be helpful, too (if any error messages pop up).

Please note that we require accounts to be linked to a discord account before logging in.

You can find out more (and open issues) on our official Discord Server: https://discord.gg/bymrefitted

Best,
Jannick

**Comment by nicco2803** [comment]
T Y didn’t know can be closed..Best Nicolas Am 21.12.2024 um 20:52 schrieb Jannick Oursin ***@***.***>:﻿
Hi @nicco2803 ,
can you please describe what happens when you try to log in? A screenshot would be helpful, too (if any error messages pop up).
Please note that we require accounts to be linked to a discord account before logging in.
You can find out more (and open issues) on our official Discord Server: https://discord.gg/bymrefitted
Best,
Jannick

**Comment by AleksitjVladica** [comment]
That web link to server of web site - Discord; does not work.
