### ISSUE TITLE
Buildings stacking on top of each other

### ISSUE THREAD

**Issue by W1GZY** [bym-refitted/backyard-monsters-refitted#36]
**Describe the bug**
![bluetenit](https://github.com/bym-refitted/backyard-monsters-refitted/assets/96368352/4938a406-c165-472c-ab62-45e4e32293a3)

**To Reproduce**
Havent been able to reproduce yet. Possible _Darlax97_ from discord could help as he has some experience with this bug.

**Expected behavior**
Buildings shouldn't be able to stack or merge with each other in any way.

**Screenshots**
![Screenshot_3](https://github.com/bym-refitted/backyard-monsters-refitted/assets/96368352/72fda249-fc84-4984-9c43-9e5eb86d760d)
![Screenshot_4](https://github.com/bym-refitted/backyard-monsters-refitted/assets/96368352/7dbbcc74-42e5-4dd1-9015-928d6127a2c2)

**Desktop (please complete the following information):**
Not quite sure about OS and flash player. Contact _Darlax97_

**Comment by React1-X** [comment]
Details from Darlaz:

"so i opened the yard planner and started to build a base for save file 2. the current base i saved at file 1. while moving around objects, it suddenly noticed, that i placed a wall in the townhall. so i moved it out and back in and still worked. than i tryed with different objects and it just worked with all. and one thing led to another 😅 one time i accidently saved in savefile 1 instead of 2 and removed the current base too 🙃 because base building takes a lot of time, i still have this glitchy base 😅

and yes, i tryed it with the refitted swf file to, it also works there. i believe the issue is causes by flashplayer itsself, winlator or the hardware, that no object in the yard planner has collision. in normal view, objects have collision 🙂"

**Comment by React1-X** [comment]
Closing this issue as I cannot even begin to imagine fixing this lmao, it's a bug from the original and it's due to poor programming on the client and Flash. If it gets really bad we can return to it, otherwise we can just ban/wipe players who are purposely exploiting this
